### ISSUE TITLE
How to do an analyses for two categorical variables in Phytools?

### ISSUE THREAD

**Issue by emxly86** [liamrevell/phytools#100]
Hi everyone! Just wondering if there is a way to do something similar to a chi square analyses in Phytools? I have two sets of categorical variables that I am trying to compare, and I can't seem to figure out how using Phytools. Thanks so much in advance!!

**Comment by liamrevell** [comment]
Maybe you're thinking of Pagel's (1994) binary correlation test (`phytools::fitPagel`) or the _D_-test by Huelsenbeck et al. (2003) (`phytools::Dtest`).
