### ISSUE TITLE
read.simmap and write.simmap are not working properly

### ISSUE THREAD

**Issue by J-Moravec** [liamrevell/phytools#11]
I am attempting to save simmap simulations made by make.simmap.

When using nsim > 1, I get:
`Error: evalutaion nested too deeply: infinite recursion / options(expressions=)?`
Seems like some recursion is not working properly?

If using nsim = 1, it is saved. However, when I attempt to read it again (without text, I hope that code is smart enough to be able to write and read same object), I get:
`Error in start:end : NA/NaN argument`

**Comment by liamrevell** [comment]
I believe this should be fixed now.

**Comment by liamrevell** [comment]
I am closing this issue.
