### ISSUE TITLE
collapse.to.star not working as before

### ISSUE THREAD

**Issue by dominicev** [liamrevell/phytools#110]
Had some code to collapse branches based on node values which was working fine a few months ago but no longer. No error codes or anything but it simply doesn't return the tree with any of the corresponding nodes collapsed.

Tried updating R and all packages and still, same issue.

Below is an example where the resulting tree has no collapsed nodes.

```
data("wasp.trees")
tree<-wasp.trees[[2]]
collapseList<-as.numeric(tree$node.label)<70
collapseList[1]<-FALSE
collapseList<-unlist(lapply(collapseList,function(x) ifelse(is.na(x),TRUE,x)))

{newTree<-tree
for(i in 1:length(collapseList)){
ifelse(collapseList[i],  newTree<-collapse.to.star(newTree,i ),newTree<-newTree)
}
plot(newTree, show.tip.label = FALSE, show.node.label=TRUE)
}
```

Even the simple example below doesn't seem to do anything

```
{newTree<-collapse.to.star(wasp.trees[[2]],5 ) 
plot(newTree, show.tip.label = FALSE, show.node.label=TRUE)}
```

**Comment by liamrevell** [comment]
Thanks @KlausVigo.
