### ISSUE TITLE
source of phylogram() in phylo.heatmap

### ISSUE THREAD

**Issue by ThomWorm** [liamrevell/phytools#111]
I'd like to modify phlo.heatmap to change some aesthetics - when I copy the source code and modify the function, the internal function phylogram() is not found - it seems this is being called from a dependency but I can't seem to find where it is coming from - do you have any suggestion?
Thanks

**Comment by liamrevell** [comment]
It's a _phytools_ function, but not exported in the namespace. Try running `phylogram<-phytools:::phylogram` before executing your modified code or substituting `phylogram` for `phytools:::phylogram` in every place that it's called.

On the other hand, if you have concrete aesthetic improvements you would like me to make to `phylo.heatmap`, please open another issue & I will see what I can do.
