### ISSUE TITLE
plotTree/plotSimmap converting underscores to spaces without option to keep underscores

### ISSUE THREAD

**Issue by AlesBucek** [liamrevell/phytools#119]
plotTree/plotSimmap converts underscores to spaces without option to keep underscores. This is sometimes nice but not always desired. Ideally, plotTree/plotSimmap should be able to pass the argument "underscore" to plot.phylo.

**Comment by liamrevell** [comment]
Dear @AlesBucek. Please try updating _phytools_ from GitHub. I believe this is now fixed with the argument `underscore=TRUE`. (It defaults to `FALSE` in which the underscores are plotted as spaces.) Let me know if you run into any difficulties. -- Liam
