### ISSUE TITLE
error in make.simmap when using pi argument

### ISSUE THREAD

**Issue by santiagombv** [liamrevell/phytools#12]
Hi Liam, 

I am attempting to set the prior distribution on the root node of the tree, pi = c(0.66, 0.34)

Q<-matrix(c(-1,1,1,-1),2,2)
rownames(Q)<-colnames(Q)<-letters[1:2]
tree<-pbtree(n=100,scale=1)
tree<-sim.history(tree,Q)
mtrees<-make.simmap(tree,tree$states, nsim=100, model="ARD", pi = c(0.66, 0.34))

I get the error (in Spanish, sorry):
Error in getPars(bt, xx, model, Q = NULL, tree, tol, m, pi = pi, ...) : 
el argumento formal "pi" concuerda con múltiples argumentos especificados

It happens since the last R update (R 3.3.3). Could that be the problem?

thank you, 

Santiago

**Comment by liamrevell** [comment]
This is definitely a bug. It has to do with how the argument is being passed internally, so it should not affect the function if the default is being used. As soon as I can I will work on fixing this.

**Comment by liamrevell** [comment]
I think I have finally fixed this bug. I posted details of the fix on my blog: http://blog.phytools.org/2017/03/bug-fixes-for-non-flat-prior-on-root.html.

**Comment by liamrevell** [comment]
I'm going to close this thread.
