### ISSUE TITLE
Error when using "ContMap"

### ISSUE THREAD

**Issue by loaizarachnid4** [liamrevell/phytools#121]
Hi Liam, 

I encountered an error when trying to implement the "ContMap" function. I used the same exact code, data, and tree two weeks prior and it worked fine. However, after running the following:

contMap(tree,length,method="anc.ML")

I now get this error: 

Error in optim(c(sig2, a, y, rep(mean(x), length(xx))), fn = likelihood,  : 
  L-BFGS-B needs finite values of 'fn'

Any clue about how to resolve this would be very helpful.

Thanks ahead for your time.

**Comment by liamrevell** [comment]
Dear @loaizarachnid4. Can you share a reproducible example -- perhaps with your tree or dataset, or a different tree & dataset that reiterate the error? You can post or send to me via email. Thx.
