### ISSUE TITLE
R4.2.2 for windows and Rstudio crash every time I library phytools

### ISSUE THREAD

**Issue by syuu2021** [liamrevell/phytools#122]
Hi, I got a problem that R will crash when I try to library phytools, no matter in R console or Rstudio. In R console, it will crash diretcly without any notes. In Rstudio, it will say R session aborted when noted ape and maps are libraried.
![image](https://user-images.githubusercontent.com/96479674/206397516-629af343-b7c5-4f48-86f1-4dee00b06d04.png)

I found this topic: https://stackoverflow.com/questions/46305620/why-is-r-crashing-when-i-try-to-import-certain-packages
but I only have one lib path, and I deleted and reinstalled ape and maps and phytools, the situation still happens.

please, any one have any idea?

**Comment by syuu2021** [comment]
use commands like phytools::function also fail the work, and if "phytools::function" exists in Rscript, the Rstudio will directly fail again after reboot. Even I didn't run that command after reboot.

**Comment by syuu2021** [comment]
And if "phytools::function" exists in Rscript, if I reopen Rstudio, the Rstudio will directly crash after a few seconds.

**Comment by liamrevell** [comment]
Dear @syuu2021. Can you indicate whether or not this has resolved? I am not able to duplicate the error with either the CRAN or latest GitHub version of _phytools_. Thx.

**Comment by syuu2021** [comment]
Hi, thanks for your reply. Good news: It no longer happens again on my another computer. So, this problem is probably my fault.
But I can't use the original computer recently. So, I will check it again after a few days.
Thanks again for your reply.

**Comment by liamrevell** [comment]
Terrific.
