### ISSUE TITLE
Create github page

### ISSUE THREAD

**Issue by brunomioto** [liamrevell/phytools#126]
Hi!

What do you think about creating a github page with {usethis} package?

Currently it's difficult to find all the functions and code for all the package.
To create the github page you just need to run `usethis::use_pkgdown_github_pages()`

**Comment by liamrevell** [comment]
Seems like a nightmare.

**Comment by brunomioto** [comment]
usethis makes all the work for you, and we can search inside it. It uses the readme as main page and each function documentation. But it's ok if you don't want, maybe one day!
