### ISSUE TITLE
wrong scale bar size in plot.cophylo

### ISSUE THREAD

**Issue by dvs** [liamrevell/phytools#127]
Hi,

I noticed that cophylo plot has slightly wrong size of its scale bars.
Scale bars also depend on the fsize parameter. See the code example below.
Perhaps, this discrepancy is caused by tree rescaling in phylogram function.

<----- cut here ----->
library(phytools)

a <- read.tree(text = "(a:0.5,(b:0.5,c:0.5):0.5);")
b <- read.tree(text = "((a:0.5,b:0.5):0.5,c:0.5);")

pdf('plot1.pdf')
obj <- phytools::cophylo(a, b)
plot(obj, fsize=1, scale.bar=c(1,1))
dev.off()

pdf('plot2.pdf')
obj <- phytools::cophylo(a, b)
plot(obj, fsize=5, scale.bar=c(1,1))
dev.off()

**Comment by liamrevell** [comment]
Hello @dvs. Thanks for this report. I will look into it.

**Comment by liamrevell** [comment]
This should now be fixed on GitHub. Unfortunately, I just submitted a _phytools_ update to CRAN, so (unless my current submission is bounced) this fix will not be in the CRAN _phytools_ version until the next update. Please give me a thumbs-up if fixed. Thanks for the report.
