### ISSUE TITLE
Error in matexpo(Q * EL[i]) : NA/NaN/Inf in foreign function call (arg 1)

### ISSUE THREAD

**Issue by xuechunxu** [liamrevell/phytools#132]
Hi,

I estimated ancestral character states for discretely valued traits. But got the error:
`Error in matexpo(Q * EL[i]) : NA/NaN/Inf in foreign function call (arg 1)
In addition: Warning messages:
1: In log(comp[-TIPS]) : NaNs produced
2: In ace(x, tree, model = "ER", type = "discrete") :
  model fit suspicious: gradients apparently non-finite`

Here is my command line:
![image](https://user-images.githubusercontent.com/23622076/234539139-4188585e-1462-46af-93d0-3d8fb2462247.png)
![image](https://user-images.githubusercontent.com/23622076/234539471-0e4abe08-04da-4bf2-8f33-3d7f95d185a3.png)

This is my niche file, these are five niche types
![image](https://user-images.githubusercontent.com/23622076/234540225-be0f704c-1b0d-42eb-ac4d-88cf34a7b4ae.png)

Looking forward to your reply!

Chun Xu

**Comment by liamrevell** [comment]
`ace` is not a _phytools_ function -- it's a function of the _ape_ package by Emmanuel Paradis; _however_, it **is** possible to do marginal ancestral state reconstruction using _phytools_ and that's what I'd probably recommend. In that case, you workflow would look roughly as follows:

`fitER<-fitMk(tree,x,model="ER")
marginal_ER<-ancr(fitER)`

Please try that & let me know what you discover.

**Comment by xuechunxu** [comment]
Thanks for your reply.

I ran the command, but got the error:
`marginal_ER<-ancr(fitER)
Error in ancr(fitER) : could not find function "ancr"`


Is my phytools need to be updated? 
This is my phytools version:
![image](https://user-images.githubusercontent.com/23622076/234742000-2f68dd71-f620-4173-a0af-16e76126128d.png)

Thank you again!

Chun Xu

**Comment by liamrevell** [comment]
Yes, you should install the _remotes_ package from CRAN and then run

```
remotes::install_github("liamrevell/phytools")
```

to update _phytools_ from GitHub.

**Comment by liamrevell** [comment]
(Although I see some problem with your data based on the output from `fitMk` so you try to get that sorted out first.)

**Comment by xuechunxu** [comment]
Thanks for your reply.

I was so confused about the error. Is there a problem with my input file? Could you check it for me? Attach please find the tree and niche annotation.

Thank you ery much.

Chun Xu
发件人: Liam J. ***@***.***>
发送时间: 2023年4月27日 10:13
收件人: ***@***.***>
抄送: chunxu ***@***.***>; ***@***.***>
主题: Re: [liamrevell/phytools] Error in matexpo(Q * EL[i]) : NA/NaN/Inf in foreign function call (arg 1) (Issue #132)


(Although I see some problem with your data based on the output from fitMk so you try to get that sorted out first.)

―
