### ISSUE TITLE
nodelabels mixes up existing node labels 

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [liamrevell/phytools#134]
The nodelabels function for plotting cophylo trees mixes up the node labels. I cannot see why this is or how to solve it. Thanks.

```
tree1<-ape::read.tree("MO-conc.rename.tree")

tree2<-ape::read.tree("mo-bmge-gcf.rename.tree")

#get outgroup node number

outg<-'377952_Paraserianthes_lophantha'

c<-0
for (x in tree1$tip.label){
  c=c+1
  if (x==outg){rootnum1<-c}
}

print(rootnum1)

tree1<-reroot(tree1, rootnum1,position=0.5*tree1$edge.length[which(tree1$edge[,2]==rootnum1)])

rootedge.to.singleton(tree1)

c<-0
for (x in tree2$tip.label){
  c=c+1
  if (x==outg){rootnum2<-c}
}

print(rootnum2)

tree2<-reroot(tree2, rootnum2, position=0.5*tree2$edge.length[which(tree2$edge[,2]==rootnum2)])

rootedge.to.singleton(tree2)

ladderize(tree1)

ladderize(tree2)

plotTree(tree1,color=NULL,fsize=0.5,ftype="reg",lwd=1,pts=FALSE,node.numbers=TRUE)

plotTree(tree2,color=NULL,fsize=0.5,ftype="reg",lwd=1,pts=FALSE,node.numbers=TRUE)


hp.cophylo<-cophylo(tree1,tree2,rotate=FALSE)  #angtree on left

pdf(file="mo_vs_.pdf",width=50,height=80)

plot(hp.cophylo,link.type="curved",link.lwd=2,link.lty="solid",link.col=make.transparent("red",0.6),fsize=2.8)
nodelabels.cophylo(tree1$node.label,which="left",frame="none",cex=1.8)
nodelabels.cophylo(tree2$node.label,which="right",frame="none",cex=1.8)

dev.off()
```

tree1:
(378018_Acacia_floribunda:0.0193906415,(((((((((((((((((((((377973_Acacia_drummondii_Lindl._subsp._Drummondii:0.0126074493,378004_Acacia_nigricans:0.0100440341)100/30.4:0.0022096849,(377959_Acacia_preissiana:0.0094433489,378007_Acacia_pulchella_R.Br._var._pulchella:0.0133165894)100/28.9:0.0025345496)100/17.4:0.0024767406,((377974_Acacia_nervosa:0.0114402046,377960_Acacia_celastrifolia:0.0093320799)100/23.2:0.0014753828,(378005_Acacia_divergens:0.0153818538,377966_Acacia_truncata:0.0075033302)100/42.9:0.0052410781)100/21.8:0.0028747435)100/11.8:0.0023949545,378009_Acacia_alata_var._biglandulosa:0.0178063368)95/3.5:0.0006088307,((378047_Acacia_pravifolia:0.0101211793,377962_Acacia_scalena:0.0079669091)100/45:0.0037262028,134513neb_Acacia_spinescens:0.0148953644)100/25.2:0.0033493798)100/4.02:0.0013976747,(377978_Acacia_saligna:0.0152671702,((134519neb_Acacia_ampliceps:0.0087747569,378010_Acacia_rostellifera:0.0067645653)100/29.5:0.0016280150,377965_Acacia_orbifolia:0.0075948187)100/51.6:0.0071863852)93/7.55:0.0007866315)100/3.72:0.0006219167,(378039_Acacia_longipedunculata:0.0084635802,134518neb_Acacia_lycopodiifolia:0.0115297588)100/54.6:0.0070964504)100/6.23:0.0020379295,(378014_Acacia_victoriae_Benth._subsp._Victoriae:0.0178756692,134517neb_Acacia_pyrifolia:0.0187194126)100/18.4:0.0033942047)85/1.24:0.0005134170,(((378034_Acacia_ulicifolia:0.0141111446,377972_Acacia_longispinea:0.0136056841)80/14.7:0.0012065070,((378040_Acacia_excelsa_Benth._subsp._Excelsa:0.0134430043,378025_Acacia_alleniana:0.0150132421)99/18.6:0.0015689112,377982_Acacia_juncifolia:0.0152250495)99/11.4:0.0008209280)100/28:0.0049753243,377952_Paraserianthes_lophantha:0.0136624955)67/4.22:0.0004042162)100/1.57:0.0005179843,378013_Acacia_murrayana:0.0214087503)100/0.629:0.0005536725,(377979_Acacia_anthochaera:0.0136895068,378008_Acacia_acinacea:0.0158385628)100/14.4:0.0023320235)100/0.623:0.0012301576,(378019_Acacia_pilligaensis:0.0150590954,377971_Acacia_glutinosissima:0.0121113834)100/16:0.0025360511)85/0.623:0.0005136601,((((377955_Acacia_microbotrya:0.0069054096,377998_Acacia_brachybotrya:0.0090543833)100/20.7:0.0018908259,79638_Acacia_pycnantha:0.0117528216)100/12.1:0.0020938320,((378033_Acacia_elata:0.0102208679,((378027_Acacia_fimbriata:0.0124797378,377995_Acacia_deanei_subsp._Paucijuga:0.0089817620)99/10.1:0.0012045393,(378026_Acacia_falcata:0.0090583092,(377991_Acacia_falciformis:0.0074850124,378032_Acacia_binervata:0.0072288346)100/19.6:0.0024050757)100/6.21:0.0008086422)99/2.83:0.0008692327)89/1.91:0.0004735728,378042_Acacia_conferta:0.0116918982)99/2.83:0.0008286029)100/15.7:0.0059275151,(378035_Acacia_rothii:0.0118858286,134516neb_Acacia_platycarpa:0.0111784721)100/35.4:0.0049607841)100/4.32:0.0010796711)100/0.926:0.0007620750,(((377983_Acacia_halliana:0.0091435936,377975_Acacia_ligustrina:0.0095432045)100/38.2:0.0050676298,(378006_Acacia_stenoptera:0.0110709907,377997_Acacia_trigonophylla:0.0110258598)100/41.3:0.0056303875)98/1.9:0.0006699209,378003_Acacia_crassuloides:0.0161375240)88/0.315:0.0004847117)90/0.344:0.0003882332,79784_Acacia_peuce:0.0217808252)100/0:0.0006418473,(378024_Acacia_tetragonophylla:0.0139205697,378021_Acacia_sulcata_R.Br._var._sulcata:0.0142669885)100/21.3:0.0040107549)100/0:0.0006949680,((((((((378012_Acacia_ancistrophylla_var._lissophylla:0.0141615922,378001_Acacia_melvillei:0.0086701714)100/20.7:0.0027217370,377963_Acacia_inceana_subsp._Conformis:0.0086924963)99/9.18:0.0009371291,377999_Acacia_sclerophylla_Lindl._var._sclerophylla:0.0099230661)100/11.1:0.0031936646,377953_Acacia_redolens:0.0122224390)100/3.17:0.0010615110,377992_Acacia_oswaldii:0.0129538606)100/3.14:0.0010127278,(377993_Acacia_stenophylla:0.0122766474,377968_Acacia_cyclops:0.0107671894)100/12.4:0.0020000562)100/1.57:0.0008851258,(378023_Acacia_wilhelmiana:0.0152064301,378022_Acacia_verriculum:0.0078455711)100/41.1:0.0099739626)94/0.312:0.0005803503,(((((377990_Acacia_ausfeldii:0.0057383493,377989_Acacia_verniciflua:0.0055419383)100/39.2:0.0027389464,134512neb_Acacia_paradoxa:0.0077339917)100/22.7:0.0015134068,377994_Acacia_montana:0.0081910935)100/23.6:0.0033884886,(377988_Acacia_melanoxylon:0.0093859712,377986_Acacia_lanigera_A.Cunn._var._lanigera:0.0083008141)100/18.8:0.0016229466)95/5.38:0.0010611216,378000_Acacia_genistifolia_Link_subsp._genistifolia:0.0125386900)100/2.19:0.0022779387)100/0:0.0015320641)100/0:0.0009218388,(378029_Acacia_mackeyana:0.0143091078,378046_Acacia_baueri_Benth._subsp._Baueri:0.0167274246)100/4.85:0.0010115514)100/0:0.0009007311,377976_Acacia_eremaea:0.0150475179)100/0:0.0007624082,((((((377958_Acacia_denticulosa:0.0084209451,377954_Acacia_acuminata:0.0092753777)100/29.2:0.0033812821,377964_Acacia_neurophylla_subsp._erugata:0.0111376142)100/7.23:0.0016048629,(377956_Acacia_aptaneura:0.0097061898,377977_Acacia_ramulosa_W.Fitzg._var._ramulosa:0.0110075514)100/24.1:0.0035582038)100/0.94:0.0009428211,377987_Acacia_triptera:0.0147460021)56/0.623:0.0006238873,(((378044_Acacia_calyculata:0.0126034589,(((378015_Acacia_ancistrocarpa:0.0100547197,378028_Acacia_gonocarpa:0.0141525373)100/19.5:0.0018276289,378045_Acacia_wickhamii_subsp._cassitera:0.0096220525)100/22.2:0.0034449932,378036_Acacia_crassicarpa:0.0146175332)100/14.5:0.0023399511)100/9.01:0.0030195475,(((((378020_Acacia_quadrimarginea:0.0084254288,378030_Acacia_subcontorta:0.0075580312)100/31.2:0.0038935486,377970_Acacia_trachycarpa:0.0106424027)100/7.81:0.0014931366,(((378043_Acacia_torulosa:0.0182398198,134520neb_Acacia_kelleri:0.0087508281)100/12.6:0.0015857009,(377981_Acacia_julifera_Benth._subsp._Julifera:0.0090425396,134515neb_Acacia_tumida:0.0093195726)100/10.8:0.0013084751)100/8.92:0.0026491998,134521neb_Acacia_deltoidea_subsp._deltoidea:0.0147299861)100/2.2:0.0010803713)89/0.309:0.0005156786,((((378011_Acacia_sibirica:0.0169159712,378016_Acacia_coolgardiensis:0.0136713450)80/6.17:0.0016689016,377969_Acacia_grasbyi:0.0116493339)78/2.55:0.0005148672,378037_Acacia_shirleyi:0.0117721673)80/1.27:0.0007321994,377985_Acacia_doratoxylon:0.0120216042)100/0.943:0.0009773227)87/0.313:0.0007903433,377961_Acacia_yorkrakinensis_subsp._Acrita:0.0108638690)100/1.26:0.0008015165)100/1.24:0.0014044448,((((377980_Acacia_concurrens:0.0080471098,(377996_Acacia_auriculiformis:0.0085195272,(378017_Acacia_diastemata:0.0078753815,134514neb_Acacia_colei_var._colei:0.0099035374)96/15.4:0.0012826881)71/7.35:0.0007720407)100/19.7:0.0026796496,378041_Acacia_humifusa:0.0160790864)100/15.8:0.0039240587,(377957_Acacia_merinthophora:0.0087746635,378031_Acacia_heteroneura_var._jutsonii:0.0149577981)100/24.3:0.0046114195)100/2.19:0.0015560164,378038_Acacia_guymeri:0.0151805675)39/0:0.0006302057)51/0.309:0.0005707728)100/0:0.0009231733,377967_Acacia_coriacea_subsp._pendens:0.0154557733)100/0:0.0006407864)100/2.83:0.0008963607,377984_Acacia_colletioides:0.0121653238)100/23.1:0.0044105993,378002_Acacia_oxycedrus:0.0114047863);

Tree2:
(378018_Acacia_floribunda:0.0135891027,((((((((((((((((((377973_Acacia_drummondii_Lindl._subsp._Drummondii:0.0081884148,378004_Acacia_nigricans:0.0063158231)100/24.9:0.0014686868,(377959_Acacia_preissiana:0.0059171571,378007_Acacia_pulchella_R.Br._var._pulchella:0.0091342377)100/21.6:0.0017597219)100/14.9:0.0028682740,((377974_Acacia_nervosa:0.0061512512,377960_Acacia_celastrifolia:0.0071066696)96/12.1:0.0007443637,(378005_Acacia_divergens:0.0106660703,377966_Acacia_truncata:0.0047475432)100/35.1:0.0042177527)100/13.4:0.0023182575)100/7.87:0.0019078781,378009_Acacia_alata_var._biglandulosa:0.0129751865)84/1.87:0.0006104098,((378047_Acacia_pravifolia:0.0071565828,377962_Acacia_scalena:0.0055681475)100/30.3:0.0022192582,134513neb_Acacia_spinescens:0.0095629113)100/22:0.0027676937)100/2.21:0.0012701206,(377978_Acacia_saligna:0.0105551641,((134519neb_Acacia_ampliceps:0.0056202051,378010_Acacia_rostellifera:0.0050580899)100/24.1:0.0013146349,377965_Acacia_orbifolia:0.0059258050)100/39.7:0.0053125456)94/3.72:0.0007872153)100/1.84:0.0004877276,(378039_Acacia_longipedunculata:0.0050477183,134518neb_Acacia_lycopodiifolia:0.0080916994)100/38.3:0.0050868674)100/4.04:0.0013899357,(((378034_Acacia_ulicifolia:0.0091984810,377982_Acacia_juncifolia:0.0095771165)100/12.4:0.0014489477,(378040_Acacia_excelsa_Benth._subsp._Excelsa:0.0095995978,378025_Acacia_alleniana:0.0110155384)100/9.81:0.0014606433)100/5.26:0.0009054924,377972_Acacia_longispinea:0.0095580989)100/23.3:0.0044324825)81/1.47:0.0005623076,(377952_Paraserianthes_lophantha:0.0086290826,(378014_Acacia_victoriae_Benth._subsp._Victoriae:0.0123073727,134517neb_Acacia_pyrifolia:0.0125415274)100/13.2:0.0025598558)97/0.763:0.0010424040)94/0.372:0.0004383920,378013_Acacia_murrayana:0.0156644576)83/0.372:0.0006393531,(377979_Acacia_anthochaera:0.0091848391,378008_Acacia_acinacea:0.0108110949)95/7.41:0.0017327268)100/0.738:0.0011021099,(378019_Acacia_pilligaensis:0.0106117853,377971_Acacia_glutinosissima:0.0079539002)100/10.9:0.0018062022)100/0.738:0.0005738236,((((377955_Acacia_microbotrya:0.0040682703,377998_Acacia_brachybotrya:0.0065535814)100/16.9:0.0013692890,79638_Acacia_pycnantha:0.0076786085)100/9.4:0.0018785993,(378033_Acacia_elata:0.0046759856,((378027_Acacia_fimbriata:0.0090413665,((378026_Acacia_falcata:0.0070100570,(377991_Acacia_falciformis:0.0042144536,378032_Acacia_binervata:0.0044188506)100/15.8:0.0018902673)100/3.01:0.0009891258,377995_Acacia_deanei_subsp._Paucijuga:0.0049201105)100/1.93:0.0010753793)98/1.54:0.0008707487,378042_Acacia_conferta:0.0074838387)93/0.377:0.0006304182)95/1.12:0.0010842748)100/13.2:0.0042759584,(378035_Acacia_rothii:0.0088803810,134516neb_Acacia_platycarpa:0.0070989623)100/21.9:0.0039336857)100/4.03:0.0008064595)100/0.366:0.0006174559,((377983_Acacia_halliana:0.0059973657,377975_Acacia_ligustrina:0.0054651682)100/28.9:0.0034730887,((378006_Acacia_stenoptera:0.0072866553,377997_Acacia_trigonophylla:0.0080597634)100/30.8:0.0043976451,(378003_Acacia_crassuloides:0.0112946229,79784_Acacia_peuce:0.0120232539)80/2.41:0.0009133440)99/0.37:0.0006934415)100/0.369:0.0006294565)100/0:0.0005094300,(378024_Acacia_tetragonophylla:0.0094900545,378021_Acacia_sulcata_R.Br._var._sulcata:0.0099253202)100/15.2:0.0035262247)99/0.368:0.0005335463,(((((((378012_Acacia_ancistrophylla_var._lissophylla:0.0087217625,378001_Acacia_melvillei:0.0060407810)100/14.6:0.0021007472,377963_Acacia_inceana_subsp._Conformis:0.0050319100)100/7.09:0.0007466492,377999_Acacia_sclerophylla_Lindl._var._sclerophylla:0.0060619629)100/7.81:0.0023206977,377953_Acacia_redolens:0.0075530647)62/3.75:0.0005721417,377992_Acacia_oswaldii:0.0075457046)100/2.61:0.0009329185,(377993_Acacia_stenophylla:0.0074906004,377968_Acacia_cyclops:0.0063382278)100/8.27:0.0017725857)100/1.85:0.0007409328,(((((377990_Acacia_ausfeldii:0.0027074423,377989_Acacia_verniciflua:0.0030167024)100/28.5:0.0018567078,134512neb_Acacia_paradoxa:0.0048925573)100/15.6:0.0009106576,377994_Acacia_montana:0.0054547315)100/15.5:0.0026784208,((378000_Acacia_genistifolia_Link_subsp._genistifolia:0.0072026249,377988_Acacia_melanoxylon:0.0055879509)86/3.41:0.0014102768,377986_Acacia_lanigera_A.Cunn._var._lanigera:0.0060443026)83/2.6:0.0007043384)100/2.21:0.0014193016,(378023_Acacia_wilhelmiana:0.0124680204,378022_Acacia_verriculum:0.0045096763)100/30.3:0.0078973729)84/0.738:0.0004392804)100/0.733:0.0014266996)100/0:0.0007748815,(378029_Acacia_mackeyana:0.0099132936,(377976_Acacia_eremaea:0.0092663990,378046_Acacia_baueri_Benth._subsp._Baueri:0.0111703600)96/1.15:0.0012300350)100/0.741:0.0008558317)100/0:0.0014078051,((((((377958_Acacia_denticulosa:0.0050950161,377954_Acacia_acuminata:0.0055351761)100/23.3:0.0026905265,377964_Acacia_neurophylla_subsp._erugata:0.0080633645)100/5.17:0.0010580809,(377956_Acacia_aptaneura:0.0066039420,377977_Acacia_ramulosa_W.Fitzg._var._ramulosa:0.0071594686)100/15:0.0027686031)100/1.86:0.0010487692,377987_Acacia_triptera:0.0091620405)63/0:0.0004799128,(((378044_Acacia_calyculata:0.0079009180,(((378015_Acacia_ancistrocarpa:0.0072985332,378028_Acacia_gonocarpa:0.0093977108)100/16.2:0.0018155730,378045_Acacia_wickhamii_subsp._cassitera:0.0070287088)100/13.4:0.0017884274,378036_Acacia_crassicarpa:0.0096751054)100/9.06:0.0015060856)100/6.25:0.0022246982,((((((378020_Acacia_quadrimarginea:0.0052891758,378030_Acacia_subcontorta:0.0046572258)100/21.1:0.0032097913,377970_Acacia_trachycarpa:0.0058747706)96/2.59:0.0008721367,(377985_Acacia_doratoxylon:0.0071772945,377969_Acacia_grasbyi:0.0074999872)67/2.26:0.0007592406)68/0:0.0009201690,(((378043_Acacia_torulosa:0.0142185028,134520neb_Acacia_kelleri:0.0055027825)100/9.41:0.0012876319,(377981_Acacia_julifera_Benth._subsp._Julifera:0.0051932881,134515neb_Acacia_tumida:0.0064144350)99/7.84:0.0009016473)100/7.14:0.0021040541,134521neb_Acacia_deltoidea_subsp._deltoidea:0.0091442265)100/1.87:0.0008886188)41/0:0.0005090343,((378011_Acacia_sibirica:0.0124744851,378016_Acacia_coolgardiensis:0.0094079809)97/4.96:0.0017220243,378037_Acacia_shirleyi:0.0067329873)72/0.369:0.0008481013)100/0.743:0.0011723182,377961_Acacia_yorkrakinensis_subsp._Acrita:0.0066775632)82/0.743:0.0009268784)100/1.1:0.0013507448,(((((377980_Acacia_concurrens:0.0054110124,377996_Acacia_auriculiformis:0.0047301016)54/11.7:0.0009813189,(378017_Acacia_diastemata:0.0057724553,134514neb_Acacia_colei_var._colei:0.0058741315)54/6.34:0.0007501953)100/14.6:0.0019783030,378041_Acacia_humifusa:0.0118229919)100/12.3:0.0023764574,(377957_Acacia_merinthophora:0.0048552727,378031_Acacia_heteroneura_var._jutsonii:0.0105730418)100/18.7:0.0039678455)100/2.22:0.0019840076,378038_Acacia_guymeri:0.0107222443)72/0:0.0008598895)72/0:0.0006301088)72/0:0.0009207811,(377967_Acacia_coriacea_subsp._pendens:0.0101298892,377984_Acacia_colletioides:0.0072310745)94/1.14:0.0012565986)88/0:0.0006210070)100/17.5:0.0041882007,378002_Acacia_oxycedrus:0.0067675907);

**Comment by theo-allnutt-bioinformatics** [comment]
Solved - used the edgelabels method instead as from blog:

edgelabels.cophylo(hp.cophylo$trees[[1]]$node.label[2:hp.cophylo$trees[[1]]$Nnode],edge=sapply(2:hp.cophylo$trees[[1]]$Nnode+Ntip(hp.cophylo$trees[[1]]),function(n,e) which(e==n),e=hp.cophylo$trees[[1]]$edge[,2]),frame="none",adj=c(1.2,1))

edgelabels.cophylo(hp.cophylo$trees[[2]]$node.label[2:hp.cophylo$trees[[2]]$Nnode],edge=sapply(2:hp.cophylo$trees[[2]]$Nnode+Ntip(hp.cophylo$trees[[2]]),function(n,e) which(e==n),e=hp.cophylo$trees[[2]]$edge[,2]),frame="none",adj=c(1.2,1),which="right")

**Comment by liamrevell** [comment]
Glad you were able to figure it out & would like to make it more intuitive in the future. Here is a more fully worked solution: 
[http://blog.phytools.org/2023/05/preserving-node-labels-in-plotted.html](http://blog.phytools.org/2023/05/preserving-node-labels-in-plotted.html). -- Liam
