### ISSUE TITLE
as.princomp on phy.pca using mode="cor"

### ISSUE THREAD

**Issue by aleungplants** [liamrevell/phytools#135]
```
data(anoletree)
data(anole.data)
pca<-phyl.pca(anoletree,anole.data,mode="cor")
pca
as.princomp(pca)
```

Is it just me or does running this code not work? I am getting the error:

`'names' attribute [6] must be the same length as the vector [1]`

It works when `mode="cov"`.

**Comment by liamrevell** [comment]
Should now be fixed on GitHub.
