### ISSUE TITLE
outline color argument to dotTree

### ISSUE THREAD

**Issue by HedvigS** [liamrevell/phytools#136]
I'd like to have an argument to dotTree that governs the outline of the dots. It defaults to black, but I'd like to set it to transparent/white. I want to do this because I want missing data to have white dots with white outline (i.e. be "invisible"). Given ggplot terminology, this would be called "color" (as opposed to "fill"), but that might get confusing so probably another term is needed.

In the example below, I'd like the dot for Rapanui to be white in the interior and in the outline. If there is a deep argument to phylo.heatmap or plotTree that refers to this I'd love to know, and I'll use that.

![poly_tree_example](https://github.com/liamrevell/phytools/assets/5327845/4279ab26-4588-4fd0-b611-39d83ecd87d4)

**Comment by liamrevell** [comment]
Now in _phytools_. (See post here: [http://blog.phytools.org/2023/06/control-dot-border-colors-in-phytools.html](http://blog.phytools.org/2023/06/control-dot-border-colors-in-phytools.html).)

**Comment by HedvigS** [comment]
I LOVE IT! ⭐⭐⭐⭐⭐

**Comment by HedvigS** [comment]
I've tried specifying the branch and commit, but I still don't get any effect by using the argument `border` with phytools::dotTree()


```
colours <- c("#ffffbf","#8856a7")

fmode <- as.factor(setNames(poly_tree_tip_value_df$GB409,poly_tree_tip_value_df$Name))

dotTree(tree = ladderize(poly_tree,right = T),
        x = fmode,
        colors=setNames(colours, c("0","1")),
        fsize=1, 
        legend = F,
        border="white")


```

![poly_tree_example](https://github.com/liamrevell/phytools/assets/5327845/75376992-aea3-4c32-b444-bf6f96540f44)

**Comment by liamrevell** [comment]
I cannot explain it. Try shutting down all open R sessions, restarting R, and reinstalling _phytools_ from GitHub.

**Comment by HedvigS** [comment]
Got it, will do :)!

**Comment by HedvigS** [comment]
Restarting R worked we have success!

I'm sorry I didn't think of that, I just got partially mentally blind some how. Thank you for your patience @liamrevell !

![posc test](https://github.com/liamrevell/phytools/assets/5327845/1f605a7c-28d8-465c-8b60-adaf5278c02e)
