### ISSUE TITLE
Error in optimizing with phylosig lambda 

### ISSUE THREAD

**Issue by lilyb3** [liamrevell/phytools#139]
I would like to calculate the phylogenetic signal for 2001 traits in a for loop with 81 taxa. I had no problem calculating the phylogenetic signal using Blomberg's K, but the code for lambda produces an error. 

- Traits is the trait file. 
- se.dn is the standard error in traits measured. 
- tree_pruned is the phylogenetic tree with 81 traits. 

Here is what I've done for K: 
for(i in 1:ncol(traits)){ 
  trialtrait<-setNames(traits[,i], rownames(traits))
  st_error <- setNames(se.dn[,i], rownames(se.dn))
  phylosig_mean[[i]] <- phylosig(tree_pruned,trialtrait, 
                                 test=TRUE,nsim=10000, se=st_error)
  trialtrait <- NULL
  st_error <-NULL
} 

Here is what I have tried to do for lambda: 
- meansig2 and meanKval are from the K calculations above. 

for(i in 1:ncol(traits)){ 
  trialtrait<-setNames(traits[,i], rownames(traits))
  st_error <- setNames(se.mean.dn1[,i], rownames(se.mean.dn1))
  phylosiglambda_mean[[i]] <- phylosig(tree_pruned,trialtrait, 
                                       method="lambda", test=TRUE, 
                                       se=st_error, 
                                       start= c(meansig2[i], meanKval[i]))

                                      
  trialtrait <- NULL
  st_error <-NULL
}

I've gotten the following errors: 
- "In control$fnscale <- -1 : Coercing LHS to a list": I think I solved this one by adding "control$fnscale <- -1 " to control parameters
- Convergence=52
- ERROR: ABNORMAL_TERMINATION_IN_LNSRCH

So far, I've tried to change the following with lambda but nothing seems to work : 

- Increasing maxit to 10000, 
-Playing with factr and pgtol per Chat GPT's suggestions. I went up to  factr = 1e15 and pgtol = 1e-20 but this didn't work
- I've calculated lambda without standard error values or hypothesis testing, which doesn't produce errors. Then, I removed all traits that had lambda <.001 recalculated lambda with hypothesis testing and standard error. This didn't seem to help. 
- I scaled the traits from -1 to 1 using the scale() function in R. 

I've tried troubleshooting with ChatGPT quite a bit but nothing seems to work. Do you have any suggestions? Thank you!

**Comment by liamrevell** [comment]
Hi @lilyb3. I tried trouble-shooting this for you with simulated data & was able to get a `for` loop working without too much difficulty. Perhaps if you send or post your files I may be able to help more. -- Liam

**Comment by liamrevell** [comment]
Please re-open if you still need help with this issue.
