### ISSUE TITLE
phylo.heatmap remove elements and smush

### ISSUE THREAD

**Issue by HedvigS** [liamrevell/phytools#144]
Dearest @liamrevell .

As always, big fan of your stuff.

I was wondering if you have any advice for removing items and  squeezing things together in phylo.heatmap. 

I've got this script: https://github.com/HedvigS/personal-cookbook/blob/main/R/tree_plotting_for_enock.R which makes this plot (desires noted in red). I'd like to drop the col names, drop the legend ans smush the heatmap and tree closer togther. i went looking in the code for how to do this, but I haven't get found a solution.

I realise that a function like phylo.heatmap combines several elements and calls on many other functions, so things get complex. but if there is a way of cutting such things out, i'd be very grateful to know about it.

![enock_tree_plot copy](https://github.com/liamrevell/phytools/assets/5327845/27a7da55-1f76-401e-85f5-690f98030a5b)

**Comment by liamrevell** [comment]
Unfortunately, out of the box the only suggestions I can make is to try the arguments `labels=FALSE` and `legend=FALSE`. You can use `split` (a vector) to set how much of the horizontal space of the plot you want dedicated to the phylogeny & data matrix, respectively: e.g., `split=c(0.9,0.1)`. Finally, with regard to the clade labels, try adjusting the `cladelabels` argument `offset`. Normally, this is set by default assuming the tip labels were printed -- but this can be modified. Good luck.
