### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by wang0430** [liamrevell/phytools#146]
remotes::install_github("liamrevell/phytools")
Downloading GitHub repo liamrevell/phytools@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                     
 2: CRAN packages only                      
 3: None                                    
 4: cpp11        (0.4.2   -> 0.4.6  ) [CRAN]
 5: rlang        (1.1.0   -> 1.1.1  ) [CRAN]
 6: cli          (3.4.1   -> 3.6.1  ) [CRAN]
 7: digest       (0.6.29  -> 0.6.33 ) [CRAN]
 8: Rcpp         (1.0.10  -> 1.0.11 ) [CRAN]
 9: igraph       (1.3.5   -> 1.5.1  ) [CRAN]
10: fastmatch    (1.1-3   -> 1.1-4  ) [CRAN]
11: scatterpl... (0.3-43  -> 0.3-44 ) [CRAN]
12: phangorn     (2.9.0   -> 2.11.1 ) [CRAN]
13: expm         (0.999-6 -> 0.999-7) [CRAN]
14: maps         (3.4.0   -> 3.4.1  ) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
✔  checking for file ‘/tmp/RtmpBiYxcw/remotes323cd4c8706c1/liamrevell-phytools-d2e7481/DESCRIPTION’ (369ms)
─  preparing ‘phytools’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘phytools_1.9-23.tar.gz’
   
Installing package into ‘/home/wanggl/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package ‘phytools’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 207081 Segmentation fault      R_TESTS= '/opt/R/4.3.0/lib/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpLBSETc/file328b2249a71d6'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: loadModule(module = "Fitch_mod", what = TRUE, env = ns, loadNow = TRUE)
 7: (function (ns) loadModule(module = "Fitch_mod", what = TRUE, env = ns, loadNow = TRUE))(<environment>)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch((function (ns) loadModule(module = "Fitch_mod", what = TRUE, env = ns, loadNow = TRUE))(<environment>),     error = function(e) e)
12: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
13: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
14: .doLoadActions(where, attach)
15: methods::cacheMetaData(ns, TRUE, ns)
16: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
17: asNamespace(ns)
18: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
19: loadNamespace(package = package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, partial = TRUE)
20: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
21: suppressPackageStartupMessages(loadNamespace(package = package,     lib.loc = lib.loc, keep.source = keep.source, keep.parse.data = keep.parse.data,     partial = TRUE))
22: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, compress = compress, set.install.dir = set.install.dir)
23: tools:::makeLazyLoading("phytools", "/home/wanggl/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-phytools/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/home/wanggl/R/x86_64-pc-linux-gnu-library/4.2/phytools")
**An irrecoverable exception occurred. R is aborting now ...
ERROR: lazy loading failed for package ‘phytools’
* removing ‘/home/wanggl/R/x86_64-pc-linux-gnu-library/4.2/phytools’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpBiYxcw/file323cd53ad1693/phytools_1.9-23.tar.gz’ had non-zero exit status**

**Comment by liamrevell** [comment]
Today `remotes::install_github("liamrevell/phytools")` seems to be working. Please let me know if this continues to be a problem for you & I can re-open the issue.
