### ISSUE TITLE
Problems installing in R version 3.4.1 (2017-06-30)

### ISSUE THREAD

**Issue by oeco28** [liamrevell/phytools#15]
Hi Liam,
  I am running into some issues installing from source locally (or via repository).
  Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package ‘phytools’ ...
** R
** data
** inst
** preparing package for lazy loading
Error : objects ‘neworder_phylo’, ‘neworder_pruningwise’ are not exported by 'namespace:ape'
ERROR: lazy loading failed for package ‘phytools’
* removing ‘/usr/local/lib/R/site-library/phytools’
Warning message:
In install.packages("/media/venezuela1/packages/phytools-master.tar.gz",  :
  installation of package ‘/media/venezuela1/packages/phytools-master.tar.gz’ had non-zero exit status

There seem to be some uncommented code in neworder_phylo or neworder_pruningwise that causes installation to fail. but I am not sure what could it be.
  Have you seen anything like this? I would appreciate any insight. Thanks!

Omar

**Comment by oeco28** [comment]
Sorry Liam,  just to provide some additional information. If I try using devtools I obtain the same output:

devtools::install_github("liamrevell/phytools")
Downloading GitHub repo liamrevell/phytools@master
from URL https://api.github.com/repos/liamrevell/phytools/zipball/master
Installing phytools
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  '/media/venezuela4/tmp/RtmpuxGLkD/devtools21af2c8f52c4/liamrevell-phytools-762158a'  \
  --library='/usr/local/lib/R/site-library' --install-tests 

* installing *source* package ‘phytools’ ...
** R
** data
** inst
** preparing package for lazy loading
Error : objects ‘neworder_phylo’, ‘neworder_pruningwise’ are not exported by 'namespace:ape'
ERROR: lazy loading failed for package ‘phytools’
* removing ‘/usr/local/lib/R/site-library/phytools’
Installation failed: Command failed (1)

**Comment by liamrevell** [comment]
What is your ape package version?

**Comment by oeco28** [comment]
ape_4.1

**Comment by oeco28** [comment]
Ey Liam,
  I see what you meant. I found a thread (https://www.mail-archive.com/r-sig-phylo@r-project.org/msg04929.html). There are some issues with ape after updating R. The recommendation is to re-install ape and the problem disappear. 
  I re-installed ape and then installed phytools successfully. 
thank you,
Omar

**Comment by liamrevell** [comment]
Great. Thank you for reporting.

**Comment by oeco28** [comment]
no problem!
