### ISSUE TITLE
cophylo object doesn't plot all branches

### ISSUE THREAD

**Issue by chirila** [liamrevell/phytools#16]
I am plotting two trees (one with 194 taxa, the other 262) as a cophylo object.   The tree compiles without errors.
The smaller tree plots correctly, but the larger one loses branches (see screenshot of partial tree below). This was using pdf()
![screenshot 2017-08-30 11 20 04](https://user-images.githubusercontent.com/16721991/29880227-3f04437e-8d75-11e7-97af-53ca7e7f377f.jpg)

Plotting directly to RStudio's graphics display produces the following
![screenshot 2017-08-30 11 25 36](https://user-images.githubusercontent.com/16721991/29880589-24ed467e-8d76-11e7-8434-dc51dedcd5e6.jpg)

Do you know if this is a memory/plotting issue with R, or something to do with the code?

**Comment by liamrevell** [comment]
I can't comment too much on the Rstudio error; however the other issue is a bug that has been fixed. All you need to do is update from GitHub using devtools & you should be fine.

More information can be seen on my blog: http://blog.phytools.org/2017/08/bug-fix-in-plotcophylo-for-co.html.

**Comment by chirila** [comment]
Thanks, that fixed it.
