### ISSUE TITLE
Save a phylomorphospace3d to file Rstudio

### ISSUE THREAD

**Issue by calugo** [liamrevell/phytools#24]
Hello, 
When I plot 3d morphospaces the plot always creates a pop-up window in Rstudio with no apparent way to export the plot to a file. Is there a way of achieving this fro the command line?

Sorry for the hassle,

Carlos

**Comment by Ax3man** [comment]
You might want to try `method = "static"` for a more traditional interface. When using `method = "dynamic"` the `rgl` package is used. You can save an image from that using the `rgl::rgl.snapshot` function.

**Comment by liamrevell** [comment]
Hi Carlos. This is correct that the default method using the package `rgl` to plot. There is a way to export this as a .gif (for instance, see here: http://blog.phytools.org/2013/06/new-versions-of-phytools-3d-methods.html), but I haven't tried or tested this in a while.
