### ISSUE TITLE
Small bug in make.simmap

### ISSUE THREAD

**Issue by Ax3man** [liamrevell/phytools#27]
This line in `make.simmap` contains a bug:

https://github.com/liamrevell/phytools/blob/fc709617ae7e165d1dc261b1b72321c455a1602e/R/make.simmap.R#L47

This `$` selection relies on the fact that `tip` is matched to `tip.label`. This might fail if a user has edited the `phylo` object, for example by adding another set of tip labels with alternate naming in `tree$tip.label2` (as I did).

In general it is risky to rely on automatic matching with `$`. I suggest the line should read 

`N<-length(tree[["tip.label"]]) `

Or better yet:

`N<-ape::Ntip(tree)`

Looks like the same bug as fixed in the last commit: https://github.com/liamrevell/phytools/commit/fc709617ae7e165d1dc261b1b72321c455a1602e. Searching for `length(tree$tip)` gives a lot of results!

**Comment by Ax3man** [comment]
Sorry, upon rereading this really sounds overly critical. Really appreciate the package, and I can prepare a PR to fix all of these if you'd like.

**Comment by liamrevell** [comment]
I think I have fixed all instances of this.
