### ISSUE TITLE
read.newick() fails to import singleton trees

### ISSUE THREAD

**Issue by tzakharko** [liamrevell/phytools#3]
read.newick() does not create a proper phylo representation for simple trees that consists of one root node and one leaf node (examples of such trees is found here: http://glottolog.org/static/trees/tree-glottolog-newick.txt). More specifically, the $edges it produces ends up to be a vector, where it should be a matrix. This can be fixed with a very simple patch. I prefer to post the patch here rather than open a pull request because this is such a minor change.

```
--- read.newick.R	2015-12-16 13:15:22.000000000 +0100
+++ read.newick2.R	2015-12-16 13:16:08.000000000 +0100
@@ -90,7 +90,7 @@
 		}
 	}
 	Ntip<-k-1
-	edge<-edge[!is.na(edge[,2]),]
+	edge<-edge[!is.na(edge[,2]),,drop=F]
 	edge[edge>0]<-edge[edge>0]+Ntip
 	edge[edge<0]<--edge[edge<0]
 	edge.length[is.na(edge.length)]<-0
```

**Comment by liamrevell** [comment]
I just pushed this fix. Can you check it & let me know that this works? Thanks!

**Comment by tzakharko** [comment]
Thanks for the fix, loading our data sets works now! I think this can be closed.
