### ISSUE TITLE
problem with extract.clade.simmap

### ISSUE THREAD

**Issue by baptelie** [liamrevell/phytools#34]
Hi,
I think there is a little bug with the function extract.clade.simmap, the returned tree has the same tree$Nnode and tree$node.label attributes as the input tree.

**Comment by liamrevell** [comment]
$Nnode does seem to change (but give me a reproducible example if you think this is not the case).

Unfortunately, $node.label is not yet supported for the "simmap" object class. It would be good to add that in the future.
