### ISSUE TITLE
apeACE function

### ISSUE THREAD

**Issue by astridboehne** [liamrevell/phytools#35]
Hi Liam
I am trying out an analysis in phytools. I was trying to use the updated version of rerootingMethod that can account for polytomies.
http://blog.phytools.org/2015/06/update-to-rerootingmethod-for-ancestral.html
Now that function calls the function apeACE. I have first installed the latest phytools from CRAN and then changed to the github version. I found the function within R/make.simmap.R on your github page, however, I do not have it within the phytools library.
What would be the best way to proceed?
Thanks
Astrid

**Comment by liamrevell** [comment]
Astrid. apeACE was always just used internally & never exported to the namespace (so never meant to be accessible to the user). Now it exists only in case any other packages call it internally - all it does is wrap phytools::fitMk.
Note, however, that to call any internally used function not exported to the namespace we can always use :::. E.g., phytools:::apeACE(...).
