### ISSUE TITLE
Warning message: In log(comp[1:M + N]) : NaNs produced using rerootingMethod

### ISSUE THREAD

**Issue by astridboehne** [liamrevell/phytools#36]
Hi Liam
I have looked a bit more into the issue I have.
I have a rooted tree, no polytomies and a categorical character matrix in which I code states with probabilities. I then used the rerootingMethods function (the one in the current package version and the one you suggested to use in case polytomies are present and to which my google search for the error message led me).
Now, I am running the following, 
anc_sp_ER <- rerootingMethod(pruned.tree, Strict_13states_matrix, type = "discrete", model = "ER", tips = TRUE) 
anc_sp_SYM <- rerootingMethod(pruned.tree, Strict_13states_matrix, type = "discrete", model = "SYM", tips = TRUE) 
anc_sp_ARD <- rerootingMethod(pruned.tree, Strict_13states_matrix, type = "discrete", model = "ARD", tips = TRUE) 
and when I am running the SYM model I get the warning message, but not with the other models.
Any advice on this? 
Thanks for your help
Astrid

**Comment by liamrevell** [comment]
This is an optimization error that might be non-fatal. If it is not fatal you're probably OK. Does the analysis still produce a result?
