### ISSUE TITLE
tip label offset in fan projection

### ISSUE THREAD

**Issue by rvosa** [liamrevell/phytools#38]
Hi @liamrevell,

first of all, I think phytools is great so I'm not here to complain. But there's something I can't figure out: how do I increase the spacing between the tip names and the ends of the terminal branches? I've experimented with the `offset` argument, in the code here: https://github.com/naturalis/trait-geo-diverse-ungulates/blob/27fdf108345a77fdba0ad55c40860e10c9c25789/script/Niche_Traits.Rmd#L189-L204 - both in the `plot()` call and in `tiplabels()` but I keep getting figures like this: https://github.com/naturalis/trait-geo-diverse-ungulates/blob/27fdf108345a77fdba0ad55c40860e10c9c25789/results/maxent/bio14_contMap.pdf

The black dot on some of the tips (or really any marker that is aesthetic) is - to my taste - a bit too close to the names. How would I change that? Or is it not an option in fan projection?

Cheers,

Rutger

**Comment by liamrevell** [comment]
I just added this - although for type="fan" the offset is in character widths. This made it a lot easier to add.
