### ISSUE TITLE
plotTree.singletons and nodelabels error "last_plot.phylo" not found

### ISSUE THREAD

**Issue by jaavedm** [liamrevell/phytools#4]
Hi,

I'm facing a problem with the usage of nodelabels when used in conjunction with plotTree.singletons. My phylogenetic tree has singleton nodes, however nodelabels fails with an error message that last_plot.phylo not found. I'd really appreciate your help with solving this. My end goal is to have nodelabel plot piecharts for each of the ancestral nodes in the graph including the singleton ones.

I've attached my source code below with the necessary input data. Thanks a lot for your help.

Jaaved Mohammed
PhD student of Computational Biology
Cornell University 
## Data

[sample.txt](https://github.com/liamrevell/phytools/files/143736/sample.txt)
[sample_m.txt](https://github.com/liamrevell/phytools/files/143735/sample_m.txt)
[sampletree.txt](https://github.com/liamrevell/phytools/files/143734/sampletree.txt)
## Source 

```
library(phytools)

treefilename="sampletree.txt"
evidencefilename="sample.txt"
marginalsfilename = "sample_m.txt"

cols = c("red", "green"); names(cols)<-c(0,1)
mt = read.newick(treefilename)

evidence = read.table(evidencefilename, header=T, stringsAsFactors=F, sep="\t");
evidence <- evidence[, c("dm3", "droSim2", "droSec2", "droYak3", "droEre2", "droAna3", "dp5", "droPer2", "droWil2", "droVir3", "droMoj3", "droGri2")];
rownames(evidence) <- evidence$name;


marginals = read.table(marginalsfilename, header=F, col.names = c("nodeid", "name", "zero", "one"), stringsAsFactors=F, sep="\t");
marginals = as.matrix(marginals[, c("zero", "one")]);
colnames(marginals) <- c(0, 1);

plotTree.singletons(mt);
nodelabels(pie=marginals, piecol = cols);
**Error in get("last_plot.phylo", envir = .PlotPhyloEnv) : 
  object 'last_plot.phylo' not found**
tiplabels(pie=to.matrix(evidence,seq=c(0,1)), piecol = cols,cex=0.5);
```
## R Session Info

```

R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] phytools_0.5-10 maps_3.1.0      ape_3.4        

loaded via a namespace (and not attached):
 [1] quadprog_1.5-5          lattice_0.20-33         mvtnorm_1.0-5           msm_1.6                 MASS_7.3-45             grid_3.2.0              nnls_1.4               
 [8] nlme_3.1-124            magrittr_1.5            scatterplot3d_0.3-36    phangorn_2.0.2          Matrix_1.2-3            splines_3.2.0           tools_3.2.0            
[15] igraph_1.0.1            plotrix_3.6-1           parallel_3.2.0          numDeriv_2014.2-1       survival_2.38-3         mnormt_1.5-3            clusterGeneration_1.3.4
[22] animation_2.4           expm_0.999-0
```

**Comment by jaavedm** [comment]
I updated my version of phytools to 0.5.18 and now I'm able to get past the last_plot.phylo error. However, now I'm seeing that nodelabels does not label the singleton node with pie charts (see attached pdf). Is there a way I can get these nodes labeled? 

Thanks.

[sampletree.pdf](https://github.com/liamrevell/phytools/files/145972/sampletree.pdf)

**Comment by liamrevell** [comment]
I have now fixed plotTree.singletons to be compatible with nodelabels & tiplabels in ape. More details can be seen on my blog: http://blog.phytools.org/2017/03/using-apenodelabels-with.html. I am closing this issue.
