### ISSUE TITLE
reroot() does not pass edgelabels = TRUE to root()

### ISSUE THREAD

**Issue by miltontan** [liamrevell/phytools#40]
It seems like ape allows for specifying whether node labels specify edgelabels using edgelabels = TRUE, which is important for bootstrap values. I think the default behavior is edgelabels = FALSE. It looks like edgelabels = TRUE happens to be a setting that I wanted to set for rerooting a tree, but I was trying to use reroot in phytools to root on a branch. It looks like reroot doesn't allow passing that argument through to root.

**Comment by liamrevell** [comment]
I believe this is now fixed on GitHub.
