### ISSUE TITLE
objective: 0 when running phylo.to map

### ISSUE THREAD

**Issue by XHuang043** [liamrevell/phytools#41]
Hi Liam,

I keep getting 'objective: 0' but I cannot find the problem. I'm quite sure that there's no problem with the structure or rownames.

> head(site)
                        lat   long
Ficedula narcissina 39.4834 115.25
Ficedula narcissina 39.4834 115.25
Ficedula narcissina 39.4834 115.25
Ficedula narcissina 39.4834 115.25
Ficedula narcissina 39.4834 115.25
Ficedula narcissina 39.4834 115.25
> is.matrix(site)
[1] TRUE
> setdiff(rownames(site), host.tree$tip.label)
character(0)
> obj <- phylo.to.map(host.tree, site, database = "worldHires", plot = F)
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0
objective: 0

Hope you can give some suggestions on resolving this problem. Thanks!

**Comment by liamrevell** [comment]
This is probably because your data are in a data frame & not a matrix. Change to a matrix using as.matrix( ).

**Comment by XHuang043** [comment]
Thanks for the reply, but after double checking, I'm pretty sure that it is a matrix and the rownames are similar with tip labels of the phylogenetic tree.

**Comment by liamrevell** [comment]
Does it pass is.matrix(...)? If is.matrix returns FALSE then it is not a matrix.
