### ISSUE TITLE
Error in xy.coords(x, y) : 'x' and 'y' lengths differ

### ISSUE THREAD

**Issue by Espresso4TheMind** [liamrevell/phytools#42]
It's giving me an error message. Help?

I attached a zip file with the R and data files.

![image](https://user-images.githubusercontent.com/42424986/56617373-bb90e300-65ed-11e9-8159-68a7d7dfd982.png)
![image](https://user-images.githubusercontent.com/42424986/56617444-e67b3700-65ed-11e9-95f6-2cfa33784a6b.png)
![image](https://user-images.githubusercontent.com/42424986/56617507-0e6a9a80-65ee-11e9-88f3-0741fd9d51fb.png)
![image](https://user-images.githubusercontent.com/42424986/56617535-22ae9780-65ee-11e9-9052-d3f551a4ad56.png)

[Rfiles.zip](https://github.com/liamrevell/phytools/files/3109823/Rfiles.zip)

**Comment by liamrevell** [comment]
It looks like this is fixed if you assure that the tree is fully bifurcating.
I'm trying to update phylo.to.map so that this is not required, but I'm still working on it.
Your tree does not seem to be rooted. I re-rooted it using midpoint rooting (phytools::midpoint.root).
![phylo to map](https://user-images.githubusercontent.com/6076607/57182813-08887b00-6e72-11e9-80d5-7a972fa4085c.png)
Some of the terminal edge lengths in your tree are negative which is why a couple of the tip labels seem misplaced.

**Comment by Jadziaa** [comment]
I am having similar problem, unfortunately in my case re-rooting didn't help. 
What else can I do to improve the way how my map looks?
![Screenshot 2020-03-30 at 11 07 48 PM](https://user-images.githubusercontent.com/40297172/77962200-73893e80-72db-11ea-9900-e71b8961502f.png)
Thanks a lot!

**Comment by liamrevell** [comment]
This is probably because of very long tip labels. Sorry about this. `phylo.to.map` is not a very sophisticated function. I recommend that you increase the size of your plotting device & try again. That might help.

**Comment by 544728460** [comment]
I also encountered the same problem. And i tried to increase the size of my device and reroot my tree. Still, it doesn't work. And i am sure the 'x' and 'y' lengths are same!
These are my commands:
library(phytools)
pdf(file="test.pdf",width=2500, height=2000)
tree <- read.tree("test-tree2.nwk", quote = "")
meta<-read.csv("metadata.csv")

coordmat <- data.matrix(meta[, c(2,3)])
row.names(coordmat) <- meta$sample

phylo.to.map(tree = tree, coords = coordmat, rotate=FALSE, ylim=c(15,60), xlim=c(90,130), colors=c("green","yellow"), direction="rightwards",fsize=0.5, pch = 21, cex.points=c(0.5,2),lwd=c(2,1.5),lty =2, ftype="i", from.tip=FALSE, split=c(0.3,0.5))
dev.off()



Can anyone help, please?   All used datasets are attached.
[error.zip](https://github.com/liamrevell/phytools/files/11173340/error.zip)



![image](https://user-images.githubusercontent.com/50523037/230459588-d8e0c322-62d0-4dec-a861-af5aacd53461.png)
