### ISSUE TITLE
anc.ML with missing data

### ISSUE THREAD

**Issue by santelmovasconcelos** [liamrevell/phytools#46]
Dear Liam,

I'm trying to reconstruct ancestral states of genome sizes using anc.ML with an incomplete data frame (with about 26% of the tips without genome sizes available), but I'm getting the following error message:

Error in ace(x, a, method = "pic") : 
  length of phenotypic and of phylogenetic data do not match.
Warning message:
In mean.default(x) : argument is not numeric or logical: returning NA

Thanks in advance!

Cheers,

Santelmo.

**Comment by liamrevell** [comment]
anc.ML needs x to be a numeric vector with tip labels as names. Is this true of your data?

**Comment by santelmovasconcelos** [comment]
Yes, ir is true. The analysis including only a tree with tips with the
genome size data works perfectly and I'm having trouble only when using the
approach with missing data for some tips.


Em sáb, 4 de mai de 2019 13:55, Liam J. Revell <notifications@github.com>
escreveu:

**Comment by liamrevell** [comment]
How is the missing data encoded? This should not be using NAs but by simply sending anc.ML a vector that doesn't contain all tip taxa.

**Comment by santelmovasconcelos** [comment]
I've tried both ways, using NAs and another data frame without the species
with missing data.
I can send you the tree and the csv file, if you wanna check the data.



Em sáb, 4 de mai de 2019 15:49, Liam J. Revell <notifications@github.com>
escreveu:

**Comment by liamrevell** [comment]
Neither of those is correct. It should just be a numeric vector with names. So, if your original data is in a data frame X with row names that correspond to the species names on the tree, & missing data coded as NA, you could do:

x1<-setNames(X[,1],rownames(X))
x1<-x1[!is.na(x)]

and then use x1 in anc.ML( ).
