### ISSUE TITLE
object 'Brazil.tree' not found?

### ISSUE THREAD

**Issue by lixingguang** [liamrevell/phytools#48]
> library(viridis)
Loading required package: viridisLite
> cols<-setNames(sample(viridis(n=Ntip(Brazil.tree))),
+                Brazil.tree$tip.label)
Error in setNames(sample(viridis(n = Ntip(Brazil.tree))), Brazil.tree$tip.label) : 
  object 'Brazil.tree' not found
>

**Comment by liamrevell** [comment]
This is not an object packaged with phytools. You should substitute for your own tree read from file.
