### ISSUE TITLE
The software simmap cannot be downloaded

### ISSUE THREAD

**Issue by Maotingru** [liamrevell/phytools#51]
Dear Liam,
This is a problem that has nothing to do with R code.I can't download the software from the official website of Simmap. Its official website is closed, so I would like to ask if you have the installation package of Simmap.
Thanks
Ru.

**Comment by liamrevell** [comment]
I have nothing to do with the SIMMAP software & have never downloaded it or used it. I recommend that you contact the authors of that software.
