### ISSUE TITLE
Problem with write.simmap / read.simmap

### ISSUE THREAD

**Issue by baptelie** [liamrevell/phytools#52]
Hi, I am trying to save the trees created with `make.simmap`, but when I write them with `write.simmap`, default options, -even though I don't get any error message-, I cannot read the nexus file with `read.simmap`, and I get this error message:
`Error in start:end : NA/NaN argument`
I attached a subtree saved with` write.simmap`
I am running phytools v. 0.6.99
[tree.test.txt](https://github.com/liamrevell/phytools/files/3336856/tree.test.txt)

**Comment by baptelie** [comment]
I guess I found the problem: `write.simmap` doesn't add _begin smptrees;_ at the beginning of the file, nor _end;_ in the end, which is needed by `read.simmap`

**Comment by liamrevell** [comment]
This is more or less the issue: write.simmap by default writes a different format than the default input format for read.simmap.  To read the format written by write.simmap you need to run:

trees<-read.simmap("filename",format="phylip",version=1)
