### ISSUE TITLE
cophyloplot for unequal number of tip labels between two trees

### ISSUE THREAD

**Issue by Jigyasa3** [liamrevell/phytools#53]
Hey @liamrevell 

Is it possible to plot a cophyloplot of two trees of unequal tip labels?
for example
tree1 has 10 tip.labels
tree2 has 20 tip.labels
association table will be like-
tip1--tip1
tip2--tip1
tip3--tip2 
          tip3
          tip4
tip5--tip5

As tree2 has 20 tip.labels, I found [http://blog.phytools.org/2019/06/update-to-plotcophylo-to-permit.html] that allows duplicate matches between two trees. But in the examples used, the two trees had same number of tip labels at all times.

Thanks

**Comment by liamrevell** [comment]
This has always been possible (or at least for a couple of years). E.g., see some examples here: http://blog.phytools.org/2017/11/more-user-control-in-co-phylogenetic.html.

**Comment by Jigyasa3** [comment]
Thank you so much! Is it possible to color the branches of the two trees before/after making them a Phylo object? My tip.labels are too large to fit in the image, so I would like to color the tree(s) branches with appropriate colors to indicate different lineages.

Thanks

**Comment by liamrevell** [comment]
This is the only way to color the edges using cophylo in phytools: http://blog.phytools.org/2017/04/coloring-edges-of-plotted-trees-in.html.
