### ISSUE TITLE
Meanings of the edge numbers? 

### ISSUE THREAD

**Issue by xie186** [liamrevell/phytools#62]
![image](https://user-images.githubusercontent.com/20909751/75379364-40e6c300-58a3-11ea-8b42-7d7ed9b723fb.png)

Work on a figure like the one shown above. Could you please tell me what does the edge number meaning? Or it's just numbers and don't mean anything? Thanks.

**Comment by liamrevell** [comment]
These numbers are node indices for the "phylo" object. There specific values are meaningless; except that (by convention) the values 1:N for N tips are assigned to external nodes, the values (N+1):(N+m) for m internal nodes are assigned to internal nodes, and the value N+1 is assigned to the global root.

**Comment by xie186** [comment]
Thank you!
