### ISSUE TITLE
How to custom change colours on the map?

### ISSUE THREAD

**Issue by tahamimo** [liamrevell/phytools#64]
I want to be able to manually assign colours once based on species/population and  once based on clades, I tried this for 64 tips:
`colours(tree$tip.label) <- c(rep("red", 15), rep("blue", 7), rep("orange", 6), rep("green", 4), rep("purple", 3), rep("white", 13))`
but it doesn't work, giving this error:

> Error in if (distinct) c[!duplicated(t(col2rgb(c)))] else c : 
>   argument is not interpretable as logical
> In addition: Warning message:
> In if (distinct) c[!duplicated(t(col2rgb(c)))] else c :
>   the condition has length > 1 and only the first element will be used

Does anybody know how to manually set colours to each tip?

**Comment by liamrevell** [comment]
I don't understand the issue or the syntax. Are you trying to plot different color tips (terminal edges) on a plotted tree? Or are you doing something with phylo.to.map? Please try to post a reproducible example so that I can help.

**Comment by tahamimo** [comment]
> I don't understand the issue or the syntax. Are you trying to plot different color tips (terminal edges) on a plotted tree? Or are you doing something with phylo.to.map? Please try to post a reproducible example so that I can help.

Hi Liam,
Thanks for answering, sorry for not being clear
yes I want to be able to colour tree tips (terminal edges) after plotting the tree,
according to your documentation, we can define different packages for colouring by which the tips will be coloured automatically based on separate clades, e.g. 

> cols<-setNames(sample(viridis(n=Ntip(Brazil.tree))), Brazil.tree$tip.label)

but I want to be able to define colours based on samples, not the clade
for example, I want all E. dilutus in the tree be the same colour...

![Inkedtree_LI](https://user-images.githubusercontent.com/50905695/82800187-ed751880-9e83-11ea-81bc-61bbd66b2816.jpg)

**Comment by tahamimo** [comment]
> I don't understand the issue or the syntax. Are you trying to plot different color tips (terminal edges) on a plotted tree? Or are you doing something with phylo.to.map? Please try to post a reproducible example so that I can help.

Or in general, if I know how can I change the default "red" colour of the lines to "white" or something invisible then I can manually draw lines myself

**Comment by liamrevell** [comment]
Hi Tahamimo. I don't even know which function you're using, so it's difficult for me to respond. Are you plotting the tree of your attached image but your want the terminal edges to have different colors based on the nominal taxon membership of each label?

**Comment by tahamimo** [comment]
Hi Liam,
This is my complete code:
```
#convert column 1 to rownames and remove column 1
rownames(gps) <- gps$name
gps <- gps[,2:3]

obj <- phylo.to.map(tree, gps, database="world",
                    regions="Iran", plot=FALSE)

plot(obj, type="phylogram", direction="rightwards", fsize=0.6)
```

**Comment by liamrevell** [comment]
It is possible to draw the linking lines with different colors. To see how, search my blog for the function `phylo.to.map` -- e.g., http://blog.phytools.org/search?q=phylo.to.map.
