### ISSUE TITLE
Tree data sets

### ISSUE THREAD

**Issue by AgustinPardo** [liamrevell/phytools#65]
Hello Liam,

Where I could find the tree data sets of the blog examples (World, Brazil, Argentina)?

Regards

**Comment by liamrevell** [comment]
These are not real data, they are simulated data meant to look like real cases for the purposes of testing the software. The code I used to simulate the data is at the end of this post on my blog: http://blog.phytools.org/2019/03/projecting-phylogenetic-tree-onto-map.html.
