### ISSUE TITLE
Line up tree node labeles

### ISSUE THREAD

**Issue by AgustinPardo** [liamrevell/phytools#67]
Hello,

I execute the next lines to get a figure:

```R
library(phytools)
library(mapdata)
gps<-read.csv("/home/agustin/workspace/covid-19/mapeo_arbol/gps_data.dat",header=TRUE)
rownames(gps) <- gps$ID
nwk=read.newick("/home/agustin/workspace/covid-19/mapeo_arbol/arbol_id_root_10.nwk")

obj<-phylo.to.map(nwk,gps[1:179,2:3],fsize=0.4,lwd=0.5,pts=FALSE,
                  direction="rightwards",database="worldHires", 
                  regions=c('Brazil', 'Colombia', 'Uruguay', 'Chile', 'Argentina', 'Peru',"Falkland"), 
                  rotate=FALSE)

```
I get this figure:

![Screenshot from 2020-06-02 17-04-13](https://user-images.githubusercontent.com/14830537/83566205-015cf200-a4f6-11ea-8e32-003712223948.png)

Do you know how to line up the tree node labels as you made in you figures:

![Screenshot from 2020-06-02 17-28-16](https://user-images.githubusercontent.com/14830537/83566496-79c3b300-a4f6-11ea-9be8-41984497ebb0.png)

Regards

Agustin

**Comment by liamrevell** [comment]
Agustin. The function plots your input tree, so most likely your input tree does not have tips that line up. If you want them to line up, you need to input an ultrametric tree to the function. If the current edge lengths don't mean anything (it looks like they all have the same length) you could use the arbitrary branch lengths of `compute.brlen` in the *ape* package. For instance:
```
 obj<-phylo.to.map(compute.brlen(nwk),gps[1:179,2:3],fsize=0.4,lwd=0.5,pts=FALSE,
                  direction="rightwards",database="worldHires", 
                  regions=c('Brazil', 'Colombia', 'Uruguay', 'Chile', 'Argentina', 'Peru',"Falkland"), 
                  rotate=FALSE)
```

**Comment by AgustinPardo** [comment]
That works perfectly! Many thanks!
