### ISSUE TITLE
Can't add optional arguments to sim.multiCtt/sim.ctt

### ISSUE THREAD

**Issue by stfriedman** [liamrevell/phytools#71]
Example from the phytools blog post:

tree <- pbtree(n=200, scale=100)
Q <- matrix(c(-0.004,0.002,0.002,
             0.002,-0.004,0.002,
             0.002,0.002,-0.004),3,3)
rownames(Q) <- colnames(Q)<-letters[1:3]
nulo <- sim.multiCtt(tree, Q, nsim=100, segments = 100)

The additional segments argument in the last line of code doesn't carry through to the internal call of ctt(). Thus, the simulations always run in increments of 20 regardless of user specification.

**Comment by liamrevell** [comment]
Hi Sarah. I believe this is fixed now if you update phytools from GitHub. 
I'm very curious how you're using ctt as I don't think this is a published method.
- Liam
