### ISSUE TITLE
plotTree.wBars and type="fan" now thows a 'rep' error

### ISSUE THREAD

**Issue by maxfarrell** [liamrevell/phytools#72]
Hi Liam, 

I previously was using the function plotTree.wBars and  type="fan" to plot a set of circular trees showing species-specific effects from a model:

`plotTree.wBars(tree, x=phy_effects, type="fan", scale=20, width=1.0, border=0)`

This worked the last time I rant the code, but after I upgraded to R 4.0.0 and phytools 0.7.20, I get the following error:

`Error in rep(" ", offset) : invalid 'times' argument`

The function works if I remove the `type="fan"` argument, but I have fairly large phylogenies so and like to plot circular trees to save space.

Thanks for a great function (and package) !

**Comment by liamrevell** [comment]
Hi Max. I suggest you update *phytools* to either the latest CRAN version (0.7-47) or the current GitHub development version (which can be done using *devtools*). This bug has already been fixed. - Liam
