### ISSUE TITLE
plotSimmap does not respect show.tip.label = FALSE

### ISSUE THREAD

**Issue by SimonGreenhill** [liamrevell/phytools#73]
I'm currently trying to plot a large tree with a simmap reconstruction, and there's no way to turn off tip labels (these just overplot each other and are illegible).  The `ape` argument `show.tip.label=FALSE` does not work, nor does setting `fsize` to `0` or `NULL` or `NA`.

**Comment by liamrevell** [comment]
That is correct. The clue is that `show.tip.label` is an _ape_ argument, as you say. The corresponding argument in _phytools_ is `ftype="off"`.
