### ISSUE TITLE
Installing phytools (version 0.7-47) on Mac OS 10.15.6 under R version 4.0.2 

### ISSUE THREAD

**Issue by eliamson** [liamrevell/phytools#74]
Hello,

I've updated R and all packages. Running library(phytools) gives me the error:
Error: package or namespace load failed for ‘phytools’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘mnormt’

**When installing mnormt, I get:**

trying URL 'https://cran.rstudio.com/src/contrib/mnormt_2.0.2.tar.gz'
Content type 'application/x-gzip' length 50606 bytes (49 KB)
==================================================
downloaded 49 KB

* installing *source* package ‘mnormt’ ...
** package ‘mnormt’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘mnormt’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/mnormt’
Warning in install.packages :
  installation of package ‘mnormt’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/03/ffjmq2xx0hs96hhpnck9cfbm0000gn/T/RtmpK95Nq3/downloaded_packages’

**I read online that manually installing an older version of mnormt could help, but I get the same message with for instance packageurl <- "https://cran.r-project.org/src/contrib/Archive/mnormt/mnormt_1.5-5.tar.gz"
install.packages(packageurl, repos=NULL, type="source")**

Many thanks in advance for your help, and more generally a huge thank you for the incredible code! 
Eli

**Comment by eliamson** [comment]
Ok I finally managed to install mnormt. The trick: When asked
**Do you want to install from sources the package which needs compilation? (Yes/no/cancel) **
the good answer is "no"

**Comment by liamrevell** [comment]
Yes. It looks like you do not have the developer toolkit and so the source version of mnormt wouldn't compile on your system. Glad that you figured it out.
