### ISSUE TITLE
Error in `[<-`(`*tmp*`, x == seq[i], i, value = 1) :    subscript out of bounds

### ISSUE THREAD

**Issue by ymilesz** [liamrevell/phytools#77]
Hi Liam,

  I am trying to do ASR with discrete data, and I've gotten this error 
Error in `[<-`(`*tmp*`, x == seq[i], i, value = 1) :  subscript out of bounds 
using both my own data as well as the data from this Exercise: http://www.phytools.org/Cordoba2017/ex/8/Anc-states-discrete.html

  I've used this code before so I know it worked before, I'm using R4.0.2

Thanks,

Miles

**Comment by liamrevell** [comment]
Maybe try converting your discrete character to a factor and then re-run. How text was interpreted by default in R changed between R<4.0 and R>4.0. Let me know if that does anything.

**Comment by bastianheimburger** [comment]
Hi Liam,

you made my day, again. Many thanks. I have used the `as.factor()` function and it worked perfectly.


Cheers Bastian
