### ISSUE TITLE
data format for phytools

### ISSUE THREAD

**Issue by rthapa1** [liamrevell/phytools#78]
Hi,

I want to construct a phylogenetic tree using a CSV file. I have a CSV file with row names as sample id and column names as gene id. I do have copy number value for all genes across all samples. I wonder how could I make a tree file using CSV file. It seems like phytools doesn't accept CSV file for phylogenetic tree construction. I would appreciate any suggestions.

Thanks

**Comment by liamrevell** [comment]
_phytools_ doesn't (in general) do phylogenetic inference. You might be more interested in the _phangorn_ package.
