### ISSUE TITLE
plotTree.boxplot()cuts off top and bottom of boxplot

### ISSUE THREAD

**Issue by schmitt8** [liamrevell/phytools#82]
Hi Liam,

I have a question regarding the aesthetics of plotTree.boxplot() function. Using a dataset of six taxa, the resulting plot cuts off the top and bottom of the boxplot panel. I realize that using boxwex I can reduce the width of the boxes in the boxplot, which does resolve the issue of the top and bottom being cut off, but to do so I have to reduce the box width to such an extent that the plot has tons of white space and doesn't look as good. I have looked and the plotTree.boxplot() function and tired to correct this issue by adjusting margins, etc., but I can't seem to solve the issue. I realize this is a rather small and purely aesthetic issue and that I am probably overlooking something super obvious, but I have attempted to solve on my own and would greatly appreciate any help to figure out how to keep the plot from getting cut off while keeping the default widths of the boxes.

thanks in advance,

Jonathan

with default settings:
![image](https://user-images.githubusercontent.com/33100343/98691521-1c048400-233c-11eb-9d44-35957f0926e7.png)

with reduced box width using boxwex=0.3:
![image](https://user-images.githubusercontent.com/33100343/98691812-6d147800-233c-11eb-9f77-07326a4b1d83.png)

**Comment by liamrevell** [comment]
This should now be fixed on _GitHub_ and will be in the next CRAN version of _phytools_. Thanks for the report.
