### ISSUE TITLE
Error in 'make.simmap' when 'Q="empirical"' or 'p="estimated"

### ISSUE THREAD

**Issue by Caetanods** [liamrevell/phytools#9]
This code will reproduce the error:

phytools version ‘0.5.65’, geiger version '2.0.6' and ape version '4.0'
```
library(phytools)
library(geiger)
tree <- sim.bdtree(stop="taxa", n=200)
trait <- rep(c("A","B"), each = 100)
names(trait) <- tree$tip.label
map1 <- make.simmap(tree, x=trait, model="ARD", message=FALSE) ## Runs ok.
map2 <- make.simmap(tree, x=trait, model="ARD", Q="empirical", message=FALSE) ## Error
```

**Comment by Caetanods** [comment]
Just an update. The problem seems also to happen when a value is passed to the 'pi' argument.

**Comment by liamrevell** [comment]
Yes, sorry. This is a bug that is due to how the argument is being passed internally. It has also been reported by other users but I haven't got around to fixing it yet. I will try to work on it soon.

**Comment by liamrevell** [comment]
I think I have finally fixed these bugs. The details are on my blog: http://blog.phytools.org/2017/03/bug-fixes-for-non-flat-prior-on-root.html.

**Comment by Caetanods** [comment]
Thanks a lot Liam!

**Comment by liamrevell** [comment]
I'm going to close this thread.
