### ISSUE TITLE
Changing type to cladogram within cophylo

### ISSUE THREAD

**Issue by JonathonMifsud** [liamrevell/phytools#93]
Hi Liam,

Phytools has been a wonderfully helpful package, thanks for this! I have recently been using the `cophylo` function and have been finding that specifying the `type` parameter has no effect like it typically does in the `plotSimmap` function. 

I have tried the following:
`plot(phytools::cophylo(tree1, tree2, assoc_table, type="cladogram"), ftype="off", type = "cladogram")`
Or 
`cophylo1 <- phytools::cophylo(tree1, tree2, assoc_table, type="cladogram")`
`plot.cophylo(cophylo1, ftype = "off", type="cladogram")`

Any help would be greatly appreciated!

**Comment by liamrevell** [comment]
Just added this. See my [blog](http://blog.phytools.org/2021/12/slanted-cladogram-tree-style-for-co.html) for more details.
