### ISSUE TITLE
Unable to load library(phytools) 

### ISSUE THREAD

**Issue by layhiang1995** [liamrevell/phytools#97]
Hi Liam, 

Thank you for this package. Recently I encountered problems with the phytools library as shown below:
> library(phytools)
Loading required package: ape

Attaching package: ‘ape’

The following object is masked from ‘package:Biostrings’:

    complement

Loading required package: maps
Error: package or namespace load failed for ‘phytools’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package phangorn: loadModule(module = "Fitch_mod", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "Fitch_mod": function 'Rcpp_precious_remove' not provided by package 'Rcpp'
In addition: Warning messages:
1: package ‘phytools’ was built under R version 4.0.5 
2: package ‘maps’ was built under R version 4.0.5 

May I know how I can solve this? Thank you!

**Comment by liamrevell** [comment]
My guess is that this will resolve if you update R. Try that, and let me know if it doesn't work. I have no problem reinstalling or loading phytools in R 4.1.1.

**Comment by liamrevell** [comment]
If you are still not able to load _phytools_ please let me know. Otherwise, I'll consider this issue closed.
