### ISSUE TITLE
What happens if make.simmap() gets an unrooted tree?

### ISSUE THREAD

**Issue by HedvigS** [liamrevell/phytools#98]
I have just found out that somehow, someway, at one point in my code `ape::keep.tip() `unroots my tree. This is rather odd, and I'm working on figuring out how this could be. But, funnily enough, this hasn't caused any warnings or errors for `phytools::make.simmap()`. I was trying to read through the code behind `make.simmap()` to gain insight of what might happen to an unrooted tree (midpoint rooting? something else?). I couldn't tease it out. What could be happening? It spits out a reasonable looking output,` summary() `works fine etc etc.

**Comment by HedvigS** [comment]
[(Update, I've solved the rooting problem with a workaround and opened an issue at the ape repos regarding how `ape::keep.tip/drop.tip()` unroots my tree](https://github.com/emmanuelparadis/ape/issues/32). Still curious what `make.simmap()` does with an unrooted tree since it didn't complain.)

**Comment by liamrevell** [comment]
Yes, there's no inherent problem in using an unrooted tree in `make.simmap`. The only issue I see regards fitting directional models (e.g., `model="ARD"` or a custom model with irreversible changes). This doesn't make much sense if the tree's unrooted.
